# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  version:
    uses: ./.github/workflows/version.yml
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}

  build-app-one:
    needs: [version]
    uses: ./.github/workflows/node-build.yml
    with:
      project_dir: app-one
      
  build-app-two:
    needs: [version]
    uses: ./.github/workflows/node-build.yml
    with:
      project_dir: app-two

  build-dotnet:
    needs: [version]
    uses: ./.github/workflows/dotnet.yml

  finish:
    if: always()
    needs: [build-app-one, build-app-two, build-dotnet]
    runs-on: ubuntu-latest
    name: Finish build
    steps:
      - uses: actions/checkout@v2
      - id: get_version
        uses: ./.github/actions/read-version
      - name: Finish Build Notification
        uses: slackapi/slack-github-action@v1.17.0
        with:
          payload: |
            {
              "version": "${{ steps.get_version.outputs.version }}",
              "status": "finished"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.slack_webhook_url }}
