# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  version:
    uses: ./.github/workflows/version.yml
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}

  build-app-one:
    needs: [version]
    uses: ./.github/workflows/node-build.yml
    with:
      project_dir: app-one
      
  build-app-two:
    needs: [version]
    uses: ./.github/workflows/node-build.yml
    with:
      project_dir: app-two

  build-dotnet:
    needs: [version]
    uses: ./.github/workflows/dotnet.yml

  version-test:
    needs: [version]
    runs-on: ubuntu-latest
    name: Testing version action
    steps:
      - id: test_version
        uses: ./.github/actions/read-version.yml
      - run: echo version ${{ steps.test_version.outputs.version }}
