# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-app-one:
    uses: ./.github/workflows/node-build.yml
    with:
      project_dir: app-one
      
  build-app-two:
    uses: ./.github/workflows/node-build.yml
    with:
      project_dir: app-two

  build-dotnet:
    uses: ./.github/workflows/dotnet.yml
