name: Build dotnet

on:
  workflow_call:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

  build-Consoleapp1:
    runs-on: windows-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build
      run: dotnet build --no-restore --configuration release
    - uses: actions/upload-artifact@v2
      with:
        name: ConsoleApp1
        path: ${{ inputs.project_dir }}/ConsoleApp1/bin/Release/net5.0/**/*
        if-no-files-found: error

    
