# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Node Project
    
on:
  workflow_call:
    inputs:
      project_dir:
        description: 'Path to the project'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.project_dir }}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: '12'
        cache: 'npm'
        cache-dependency-path: ${{ inputs.project_dir }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - run: ls
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ inputs.project_dir }}
        path: ${{ inputs.project_dir }}/build/**/*
        if-no-files-found: error
