# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-app-one:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'app-one'

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: '12'
        cache: 'npm'
        cache-dependency-path: app-one
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - run: ls
    - name: Install zip
      uses: montudor/action-zip@v1
    - name: Zip output
      run: zip -qq -r app-one.zip app-one/build
      working-directory: path/to/work-dir
    - uses: actions/upload-artifact@v2
      with:
        name: app-one
        path: app-one.zip
